CREATE TABLE "MediaItem" (
  "media_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tmdb_id" bigint UNIQUE,
  "media_type" varchar(10) NOT NULL,
  "original_title" text NOT NULL,
  "overview" text,
  "original_language" char(2),
  "status" varchar(50),
  "popularity" numeric(12,6) DEFAULT 0,
  "vote_average" numeric(3,1) DEFAULT 0,
  "vote_count" int DEFAULT 0,
  "poster_path" text,
  "backdrop_path" text,
  "homepage_url" text
);

CREATE TABLE "Movie" (
  "media_id" bigint PRIMARY KEY,
  "release_date" date,
  "budget" bigint DEFAULT 0,
  "revenue" bigint DEFAULT 0,
  "adult_flag" boolean DEFAULT false,
  "runtime_minutes" int,
  "collection_id" bigint
);

CREATE TABLE "TVShow" (
  "media_id" bigint PRIMARY KEY,
  "first_air_date" date,
  "last_air_date" date,
  "in_production" boolean DEFAULT false,
  "number_of_seasons" int DEFAULT 0,
  "number_of_episodes" int DEFAULT 0,
  "show_type" varchar(50)
);

CREATE TABLE "Season" (
  "season_id" BIGINT PRIMARY KEY,
  "tv_media_id" bigint NOT NULL,
  "season_number" int NOT NULL,
  "name" text,
  "air_date" date,
  "episode_count" int DEFAULT 0,
  "poster_path" text
);

CREATE TABLE "Episode" (
  "episode_id" BIGINT PRIMARY KEY,
  "season_id" bigint NOT NULL,
  "episode_number" int NOT NULL,
  "name" text,
  "air_date" date,
  "runtime_minutes" int,
  "overview" text,
  "still_path" text
);

CREATE TABLE "Person" (
  "person_id" BIGINT PRIMARY KEY,
  "tmdb_id" bigint UNIQUE,
  "name" text NOT NULL,
  "gender" smallint,
  "biography" text,
  "birth_date" date,
  "death_date" date,
  "place_of_birth" text,
  "profile_path" text
);

CREATE TABLE "Actor" (
  "person_id" bigint PRIMARY KEY,
  "acting_debut_year" int
);

CREATE TABLE "CrewMember" (
  "person_id" bigint PRIMARY KEY,
  "primary_department" varchar(50)
);

CREATE TABLE "Company" (
  "company_id" BIGINT PRIMARY KEY,
  "tmdb_id" bigint UNIQUE,
  "name" text NOT NULL,
  "origin_country" char(2),
  "description" text,
  "logo_path" text
);

CREATE TABLE "Collection" (
  "collection_id" BIGINT PRIMARY KEY,
  "tmdb_id" bigint UNIQUE,
  "name" text NOT NULL,
  "overview" text,
  "poster_path" text,
  "backdrop_path" text
);

CREATE TABLE "Genre" (
  "genre_id" BIGINT PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "MediaGenre" (
  "media_id" bigint NOT NULL,
  "genre_id" bigint NOT NULL
);

CREATE TABLE "MediaCompany" (
  "media_company_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_id" bigint NOT NULL,
  "company_id" bigint NOT NULL,
  "role" varchar(20) NOT NULL
);

CREATE TABLE "TitleCasting" (
  "casting_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_id" bigint NOT NULL,
  "person_id" bigint NOT NULL,
  "character_name" text,
  "cast_order" int
);

CREATE TABLE "EpisodeCasting" (
  "casting_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "episode_id" bigint NOT NULL,
  "person_id" bigint NOT NULL,
  "character_name" text,
  "cast_order" int
);

CREATE TABLE "TitleCrewAssignment" (
  "crew_assignment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_id" bigint NOT NULL,
  "person_id" bigint NOT NULL,
  "department" varchar(50),
  "job_title" varchar(100)
);

CREATE TABLE "EpisodeCrewAssignment" (
  "crew_assignment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "episode_id" bigint NOT NULL,
  "person_id" bigint NOT NULL,
  "department" varchar(50),
  "job_title" varchar(100)
);

CREATE UNIQUE INDEX ON "Season" ("tv_media_id", "season_number");

CREATE UNIQUE INDEX ON "Episode" ("season_id", "episode_number");

CREATE UNIQUE INDEX ON "MediaGenre" ("media_id", "genre_id");

CREATE INDEX ON "MediaGenre" ("media_id");

CREATE INDEX ON "MediaGenre" ("genre_id");

CREATE UNIQUE INDEX ON "MediaCompany" ("media_id", "company_id", "role");

CREATE INDEX ON "MediaCompany" ("media_id");

CREATE INDEX ON "MediaCompany" ("company_id");

CREATE UNIQUE INDEX ON "TitleCasting" ("media_id", "person_id");

CREATE INDEX ON "TitleCasting" ("media_id");

CREATE INDEX ON "TitleCasting" ("person_id");

CREATE UNIQUE INDEX ON "EpisodeCasting" ("episode_id", "person_id");

CREATE INDEX ON "EpisodeCasting" ("episode_id");

CREATE INDEX ON "EpisodeCasting" ("person_id");

CREATE UNIQUE INDEX ON "TitleCrewAssignment" ("media_id", "person_id", "job_title");

CREATE INDEX ON "TitleCrewAssignment" ("media_id");

CREATE INDEX ON "TitleCrewAssignment" ("person_id");

CREATE UNIQUE INDEX ON "EpisodeCrewAssignment" ("episode_id", "person_id", "job_title");

CREATE INDEX ON "EpisodeCrewAssignment" ("episode_id");

CREATE INDEX ON "EpisodeCrewAssignment" ("person_id");

COMMENT ON COLUMN "MediaItem"."media_type" IS 'valid: movie | tv';

COMMENT ON COLUMN "MediaCompany"."role" IS 'production | distribution | network | other';

ALTER TABLE "Movie" ADD FOREIGN KEY ("media_id") REFERENCES "MediaItem" ("media_id") ON DELETE CASCADE;

ALTER TABLE "TVShow" ADD FOREIGN KEY ("media_id") REFERENCES "MediaItem" ("media_id") ON DELETE CASCADE;

ALTER TABLE "Season" ADD FOREIGN KEY ("tv_media_id") REFERENCES "TVShow" ("media_id") ON DELETE CASCADE;

ALTER TABLE "Episode" ADD FOREIGN KEY ("season_id") REFERENCES "Season" ("season_id") ON DELETE CASCADE;

ALTER TABLE "Actor" ADD FOREIGN KEY ("person_id") REFERENCES "Person" ("person_id") ON DELETE CASCADE;

ALTER TABLE "CrewMember" ADD FOREIGN KEY ("person_id") REFERENCES "Person" ("person_id") ON DELETE CASCADE;

ALTER TABLE "Movie" ADD FOREIGN KEY ("collection_id") REFERENCES "Collection" ("collection_id") ON DELETE SET NULL;

ALTER TABLE "MediaGenre" ADD FOREIGN KEY ("media_id") REFERENCES "MediaItem" ("media_id") ON DELETE CASCADE;

ALTER TABLE "MediaGenre" ADD FOREIGN KEY ("genre_id") REFERENCES "Genre" ("genre_id") ON DELETE CASCADE;

ALTER TABLE "MediaCompany" ADD FOREIGN KEY ("media_id") REFERENCES "MediaItem" ("media_id") ON DELETE CASCADE;

ALTER TABLE "MediaCompany" ADD FOREIGN KEY ("company_id") REFERENCES "Company" ("company_id") ON DELETE CASCADE;

ALTER TABLE "TitleCasting" ADD FOREIGN KEY ("media_id") REFERENCES "MediaItem" ("media_id") ON DELETE CASCADE;

ALTER TABLE "TitleCasting" ADD FOREIGN KEY ("person_id") REFERENCES "Actor" ("person_id") ON DELETE CASCADE;

ALTER TABLE "EpisodeCasting" ADD FOREIGN KEY ("episode_id") REFERENCES "Episode" ("episode_id") ON DELETE CASCADE;

ALTER TABLE "EpisodeCasting" ADD FOREIGN KEY ("person_id") REFERENCES "Actor" ("person_id") ON DELETE CASCADE;

ALTER TABLE "TitleCrewAssignment" ADD FOREIGN KEY ("media_id") REFERENCES "MediaItem" ("media_id") ON DELETE CASCADE;

ALTER TABLE "TitleCrewAssignment" ADD FOREIGN KEY ("person_id") REFERENCES "CrewMember" ("person_id") ON DELETE CASCADE;

ALTER TABLE "EpisodeCrewAssignment" ADD FOREIGN KEY ("episode_id") REFERENCES "Episode" ("episode_id") ON DELETE CASCADE;

ALTER TABLE "EpisodeCrewAssignment" ADD FOREIGN KEY ("person_id") REFERENCES "CrewMember" ("person_id") ON DELETE CASCADE;
